name: Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python Script
      run: python main.py
      env:
        MY_NAME:  ${{ secrets.MY_NAME }}
        MY_LASTNAME: ${{ vars.MY_LASTNAME }}